version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: castaway-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: castaway
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  supabase-db:
    image: supabase/postgres:16.1.1.17
    container_name: castaway-supabase-db
    environment:
      POSTGRES_HOST: /var/run/postgresql
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${SUPABASE_DB_PASSWORD:-postgres}
      POSTGRES_DB: postgres
      JWT_SECRET: ${JWT_SECRET:-super-secret-jwt-token-with-at-least-32-characters-long}
      JWT_EXP: 3600
    ports:
      - "54321:5432"
    volumes:
      - supabase-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  temporal-server:
    image: temporalio/auto-setup:1.22.0
    container_name: castaway-temporal
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PWD=postgres
      - POSTGRES_SEEDS=postgres
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
    ports:
      - "7233:7233"
      - "8088:8088"
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "tctl", "--address", "localhost:7233", "cluster", "health"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: ..
      dockerfile: infra/Dockerfile.web
    container_name: castaway-web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/castaway
      - SUPABASE_URL=http://supabase-db:54321
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - TEMPORAL_ADDRESS=temporal-server:7233
    depends_on:
      - postgres
      - supabase-db
      - temporal-server
    volumes:
      - ../:/app
      - /app/node_modules

volumes:
  postgres-data:
  supabase-data:
